development: &default
  adapter: postgresql
  database: app_development
  encoding: utf8
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

test:
  <<: *default
  database: app_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  database: d423rdcfh5adt7
  host: ec2-54-204-6-113.compute-1.amazonaws.com
  port: 5432
  username: ftarzigtnbfrxf
  password: Qnmu_xJxf4Upf5TDlKmYMP-aG1

staging: *deploy
