default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: c307c938df0d709ee1edcfbc3c57a1688ef6128a7ab5d2632cfd68e25bc0f509b6aa8608fc669a69981776ccb61a444f5aa09f08ab7ec8c77cb371db6f1a432d

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
